name: build R with DeepinV23 

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: git clone https://fallingstar@gitlink.org.cn/fallingstar/RwithDeepinV23
    

    - name: pack R423
      run: |
       cd RwithDeepinV23
       bash R423build.sh
       
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: R423build
        path: RwithDeepinV23/R-4.2.3.deb
        
    - name: pack R431
      run: |
       cd RwithDeepinV23
       bash R431build.sh
       
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: R423build
        path: RwithDeepinV23/R-4.3.1.deb
